### ISSUE TITLE
If the final line of the file has no linebreak, we fail to parse the file

### ISSUE THREAD

**Issue by jnthn** [edumentab/p6-pofile#1]
We could probably be a bit more forgiving about this; while the traditional convention is that such a newline should be there, some text editors leave it out.

**Comment by Altai-man** [comment]
Addressed two cases in https://github.com/edumentab/p6-pofile/commit/614420238ed0a1c8b4d22e12a2d24497fb8a3e8f
Please, write test strings if more are needed, close otherwise.

**Comment by jnthn** [comment]
I think that'll cover it; thanks!
